# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_genes_cpp <- function(BM_sn, BM_mean, zscore_sn_threshold, zscore_mean_threshold) {
    .Call(`_anglemania_select_genes_cpp`, BM_sn, BM_mean, zscore_sn_threshold, zscore_mean_threshold)
}

scaleK <- function(BM, sums, mu, delta, nrow) {
    invisible(.Call(`_anglemania_scaleK`, BM, sums, mu, delta, nrow))
}

