# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_genes_cpp <- function(BM_sn, BM_mean, zscore_sn_threshold, zscore_mean_threshold) {
    .Call(`_anglemania_select_genes_cpp`, BM_sn, BM_mean, zscore_sn_threshold, zscore_mean_threshold)
}

colmean_no_diag_FBM <- function(BM) {
    .Call(`_anglemania_colmean_no_diag_FBM`, BM)
}

colmedian_no_diag_FBM <- function(BM) {
    .Call(`_anglemania_colmedian_no_diag_FBM`, BM)
}

