# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computePValues <- function(cor_mat, df) {
    invisible(.Call(`_anglemania_computePValues`, cor_mat, df))
}

dist2mat <- function(x, bf) {
    .Call(`_anglemania_dist2mat`, x, bf)
}

matrixAddition <- function(A, B) {
    .Call(`_anglemania_matrixAddition`, A, B)
}

